version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      eslint:
        patterns:
          - "@ionaru/eslint-config"
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-plugin-*"
      types:
        patterns:
          - "@types/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /deploy
    schedule:
      interval: weekly
