version: '3'
services:

    therabot:
        build: .
        environment:
            - DEBUG
        restart: unless-stopped
        volumes:
            - ${SEARCHEVE_DATA_VOLUME:-data-volume}:/app/data

volumes:
    data-volume:
