version: '3'
services:

    server:
        build: .
        environment:
            - DEBUG
            - SEARCHEVE_PORT
        ports:
            - "${SEARCHEVE_PORT:-3000}:${SEARCHEVE_PORT:-3000}"
        restart: unless-stopped
        volumes:
            - ${SEARCHEVE_DATA_VOLUME:-data-volume}:/app/data

volumes:
    data-volume:
